---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->  dreamt I dwelt in marble halls,  
And each damp thing that creeps and crawls  
Went wobble-wobble on the walls.   

Faint odours of departed cheese,  
Blown on the dank, unwholesome breeze, 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
If I should die, think only this of me:  
   That there’s some corner of a foreign field  
That is for ever England.  There shall be  
   In that rich earth a richer dust concealed;  
A dust whom England bore, shaped, made aware,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,   
   Shining with all his might:  
He did his very best to make   
   The billows smooth and bright--   
And this was odd, because it was  
   The middle of the night.  

The moon was shining sulkily,   
   Because she thought the sun  
Had got no business to be there   
   After the day was done--   
“It’s very rude of him," she said,  
   “To come and spoil the fun!”  
   
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
rose is red  
I am boohoo  
